### ISSUE TITLE
Handling undefined values

### ISSUE THREAD

**Issue by alvivi** [justinwoo/purescript-simple-json#65]
Hi there 👋 

I'm a little surprised about how this library uses undefined as default value for `Nothing` for example. Note that `undefined` is not a valid value in JSON. http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf (Section 5 from ECMA-404):

> A JSON value can be an object, array, number, string, true, false, or null.

I'm trying to port this library to the Go backend (https://github.com/andyarvanitis/purescript-native-go-ffi/pull/7) but this use of `undefined` is producing behavior differences because there is actually no way to produce an undefined from the standard Go library.

**Comment by justinwoo** [comment]
yes, but `undefined` is a reality in dealing with Foreign values. but for example, the erlang version does this:

https://github.com/purerl/purescript-simple-json/blob/61073d864aa53293ac7907d6e46ecc1f17810f35/src/Simple/JSON.erl

**Comment by alvivi** [comment]
But the Erlang backend is also using a workaround that is also going to produce behavior differences nope? Why not just use `Foreign.Index.hasProperty` to avoid using `undefined`. As I understand it, this is just an implementation detail of the javascript backend.

**Comment by justinwoo** [comment]
behavioral differences in minute ways yes, but undefined is a value of JS values that is unavoidable and is a clear part of Foreign.

since this is not a library that should ever be a dependency of other libraries, you should also consider simply forking this library and calling it `simple-json-go` or something if this is such a huge problem. but you can also quite simply allow the existing `undefined` checks do what are basically no-ops.

cc @nwolverson has this caused any problems for you?

**Comment by justinwoo** [comment]
let me sum this up: this issue is about the encoding behavior of Maybe, which doesn't actually have real representation in JSON. the only real solution for this is:

* more documentation about what this does in various backends if need be. note that the erlang version is simply a fork with its own notes.
* tests that are agnostic to the representation of Maybe values in the runtime of various implementations. this means that tests only target round trip behavior in the case of Maybe. but these will not get tested here, as this repository only tests the default purescript implementation.

**Comment by nwolverson** [comment]
Regarding the comment "undefined is not a valid value in JSON", I don't believe simple-json ever creates JSON with `undefined`, as you say an implementation detail - I recall thinking it was a bit of a hack, IMO if there's a clean alternative it would be nice to get rid of it, but certainly not a problem for me.

The purerl version uses `null` which maybe causes the JSON encoder to omit the object key - I forget, I've never cared to distinguish null vs absent in my json. Anyway I forgot whatever I thought about this, I never even finished writing the linked comment.

**Comment by alvivi** [comment]
I think that I'm viewing this from two points of views: 

* First, semantically, if `undefined` is a value of JS values that is unavoidable and is a clear part of `Foreign`, then this should remain in the `Foreign` package not here. Or at least not as a part of the public interface. No server is going to return you an `undefined` value because is not part of the JSON standard. If you need to manage `undefined` values in `JSON` somehow, seems reasonable that you have to use `Foreign` and `Simple.Json` but not only `Simple.Json`, is not standard.
* Second, from an implementation point of view, why using `undefined` for `Maybe` when `undefined` is not in the standard a and null it is? This is going inconsistencies with other environments. Of course, you can just document and avoid testing it directly. Using `hasProperty` will help, at least for other backend implementations.

I'm not sure... but maybe the `simple-json` API is not sound in the sense that is coupling together a data type with optional parsing. That's why undefined is used here. Anyway, I'm going to close this because seems that this is actually not an issue and we can use `null` workaround and documentation.

Thanks!
